version: '3.9'
services:
  bitrix-server:
    build: .
    container_name: bitrix-server
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      DB_PORT: 3306
      DB_HOST: mysql
      DB_USER: bitrix_user
      DB_PASSWORD: 123456
      DB_NAME: bitrix_clone
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
  mysql:
    image: mysql:8
    container_name: mysql-bitrix
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bitrix_clone
      MYSQL_USER: bitrix_user
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent',
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  mysql_data:
  node_modules:
